package com.ghost.serialization.compiler.internal

import com.squareup.kotlinpoet.ClassName

/** Whole-file codegen: package/import names, class and file naming, serializer setup, source trimming and
 * generated-code hygiene. */
internal object GhostCodegenConstants {

    const val STR_JSON_CHAR_NULL = "\"\\u0000\""
    const val STR_CURLY_OPEN = "{"
    const val STR_CURLY_CLOSE = "}"
    const val STR_COLON = ":"
    const val STR_EMPTY_JSON = "{}"
    const val STR_EMPTY_ARRAY = "[]"
    const val STR_EMPTY_STRING = "\"\""
    const val STR_COMMA = ","
    const val STR_CLOSE_PAREN_FLOW = ")"
    const val STR_ABSTRACT_GHOST_SERIALIZER = "AbstractGhostSerializer"
    val BYTE_STRING_CLASS = ClassName("okio", "ByteString")
    const val STR_RAW_JSON_TYPE = "RawJson"
    const val STR_H_VAL_PREFIX = "H_"
    const val TEMPLATE_ENCODE_UTF8 = "%S.encodeUtf8()"
    const val FMT_JSON_FIELD = "\"%s\":"
    const val OKIO_PACKAGE = "okio"
    const val DECODE_RESILIENT = "decodeResilient"
    const val STR_GHOST_JSON_READER = "GhostJsonReader"
    const val STR_GHOST_YAML_SERIALIZER = "GhostYamlSerializer"
    const val STR_GHOST_YAML_WRITER = "GhostYamlWriter"
    const val STR_GHOST_YAML_FLAT_READER = "GhostYamlFlatReader"
    const val STR_ENSURE_UTF8_BYTES = "reader.ensureUtf8Bytes()"
    const val STR_BYTE_POSITION_TO_CHAR_POSITION = "reader.bytePositionToCharPosition"
    const val STR_BEGIN_ARRAY = "beginArray"
    const val STR_END_ARRAY = "endArray"
    const val STR_READ_LIST = "readList"
    const val STR_READ_SET = "readSet"
    const val STR_READ_MAP = "readMap"
    const val STR_NEXT_KEY = "nextKey"
    const val STR_SELECT_STRING = "selectString"
    const val STR_PEEK_STRING_FIELD = "peekStringField"
    const val STR_BYTESTRING_IMPORT = "ByteString.Companion.encodeUtf8"
    const val STR_KDOC_HIGH_PERF = "High-performance serializer for [%T].\n"
    const val STR_KDOC_GENERATED = "Generated by GhostSerialization. Do not modify manually.\n"
    const val STR_OPTIONS = "OPTIONS"
    const val STR_OPTIONS_PREFIX = "OPTIONS_"
    const val STR_OPTIONS_CLASS = "JsonReaderOptions"
    const val STR_TRY = "try"
    const val STR_CATCH_EXCEPTION = "catch (_: Exception)"
    const val TEMPLATE_WARM_UP_READER_INIT = "val %L = %T(\n  %S.encodeToByteArray()\n)"
    const val TEMPLATE_WARM_UP_STRING_READER_INIT = "val %L = %T(\n  %S\n)"
    const val TEMPLATE_WARM_UP_DESERIALIZE = "deserialize(%L)"
    const val STR_READER1 = "reader1"
    const val STR_READER3 = "reader3"
    const val STR_BEGIN_OBJECT_NAME = "beginObject"

    const val STR_END_OBJECT_NAME = "endObject"
    const val STR_SELECT_NAME_AND_CONSUME_NAME = "selectNameAndConsume"
    const val STR_SKIP_VALUE_NAME = "skipValue"
    const val STR_NEXT_INT_NAME = "nextInt"
    const val STR_NEXT_LONG_NAME = "nextLong"
    const val STR_NEXT_ULONG_NAME = "nextULong"
    const val STR_NEXT_ULONG_OR_NULL_NAME = "nextULongOrNull"
    const val STR_NEXT_PROTO_UINT64_NAME = "nextProtoUInt64"
    const val STR_NEXT_STRING_NAME = "nextString"
    const val STR_NEXT_DOUBLE_NAME = "nextDouble"
    const val STR_NEXT_FLOAT_NAME = "nextFloat"
    const val STR_NEXT_CHAR_NAME = "nextChar"
    const val STR_NEXT_BOOLEAN_NAME = "nextBoolean"
    const val STR_NEXT_INT_OR_NULL_NAME = "nextIntOrNull"
    const val STR_NEXT_LONG_OR_NULL_NAME = "nextLongOrNull"
    const val STR_NEXT_STRING_OR_NULL_NAME = "nextStringOrNull"
    const val STR_NEXT_BOOLEAN_OR_NULL_NAME = "nextBooleanOrNull"
    const val STR_CAPTURE_RAW_JSON_BYTES_NAME = "captureRawJsonBytes"
    const val STR_CAPTURE_RAW_JSON_NAME = "captureRawJson"
    const val STR_DECODE_BASE64_STRING_NAME = "decodeBase64String"
    const val STR_ENCODE_BASE64_STRING_NAME = "encodeBase64String"
    const val STR_CONSUME_NULL_NAME = "consumeNull"
    const val STR_IS_NEXT_NULL_VALUE_NAME = "isNextNullValue"
    const val STR_ENUM_OPTIONS = "ENUM_OPTIONS"
    const val STR_WARM_UP = "warmUp"
    const val ARG_DISCRIMINATOR = "discriminator"
    const val STR_OPT_IN = "OptIn"
    const val STR_INTERNAL_GHOST_API = "InternalGhostApi"
    const val STR_TYPE_NAME_PROP = "typeName"
    const val MARKER_CLASS = "%T::class"
    const val STR_IS_PROTO = "isProto"
    const val STR_HS_PREFIX = "HS_"
    const val COMPACT_CALL_MAX_INLINE_LENGTH = 80
    /** Empty call: `name()`. */
    const val TEMPLATE_INVOKE_EMPTY = "%L()"

    /** Compact single-arg call: `name(arg)`. */
    const val TEMPLATE_INVOKE_ONE = "%L(%L)"

    /** Multiline call open: `name(\n`. */
    const val TEMPLATE_INVOKE_OPEN = "%L(\n"

    /** Multiline typed factory open: `Type.of(\n`. */
    const val TEMPLATE_TYPED_OF_OPEN = "%T.of(\n"

    /** One positional/boolean arg per line with trailing comma. */
    const val TEMPLATE_ARG_LINE = "%L,\n"

    /** One string literal arg per line with trailing comma. */
    const val TEMPLATE_STRING_ARG_LINE = "%S,\n"

    const val STR_RAW_JSON_DECODE = "RawJsonDecode"
    const val STR_GHOST = "Ghost"
    const val STR_GHOST_WRAPPED_KEYS_CAPTURE = "GhostWrappedKeysCapture"

    const val STR_CAPTURE_WRAPPED_KEY_NAME = "captureWrappedKey"
    const val STR_NEWLINE = "\n"

    const val STR_EXT_KT = "kt"
    const val REGEX_TRIM_REDUNDANT_KOTLIN_IMPORT =
        """^import kotlin\.(String|Int|Long|Boolean|Double|Float|Byte|Short|Char|Unit|Any|Nothing|Array|OptIn|Suppress)(\..*)?\s*$"""

    /** Strips explicit `public` modifiers that KotlinPoet adds for Explicit API mode. */
    const val REGEX_TRIM_REDUNDANT_PUBLIC =
        """^(\s*)public (?=object |class |interface |fun |val |var |override |companion |data |enum |suspend |inline |operator |expect |actual )"""

    /** Replacement for [REGEX_TRIM_REDUNDANT_PUBLIC]: keep the leading indent capture group. */
    const val STR_REGEX_GROUP_1 = $$"$1"
}
