package com.ghost.serialization.compiler

/**
 * Centralized constants for the deserialization code emitters.
 *
 * Contains all string literals, templates, and identifiers used during code generation
 * to ensure consistency and eliminate magic strings across the emitter modules.
 */
internal object GhostEmitterConstants {
    const val STR_DESERIALIZE = "deserialize"
    const val STR_KDOC_DESERIALIZE = "Robust deserialization for [%T].\n"
    const val STR_READER = "reader"
    const val TEMPLATE_PEEK_TYPE = "val typeName = reader.peekStringField(%S) ?: reader.throwError(%S)"
    const val STR_MISSING_TYPE = "Missing discriminator field for sealed class"
    const val STR_WHEN_TYPENAME = "val result = when (typeName)"
    const val STR_SERIALIZER = "Serializer"
    const val TEMPLATE_DESERIALIZE_BRANCH = "%S -> %T.deserialize(reader)"
    const val STR_UNKNOWN_TYPE = "else -> reader.throwError(\"Unknown type discriminator: \$typeName\")"
    const val STR_RETURN_RESULT = "return result"
    const val TEMPLATE_RETURN_CONSTRUCTOR = "return %T(%L)"
    const val STR_NULL = "null"
    const val STR_ZERO = "0"
    const val STR_ZERO_L = "0L"
    const val STR_ZERO_D = "0.0"
    const val STR_ZERO_F = "0.0f"
    const val STR_FALSE = "false"
    const val STR_VAR_UNDERSCORE = "var _"
    const val TEMPLATE_VAR_INIT = ": %T = %L"
    const val STR_BEGIN_OBJECT = "reader.beginObject()"
    const val STR_WHILE_TRUE = "while (true)"
    const val STR_SELECT_NAME_AND_CONSUME = "val index = reader.selectNameAndConsume(OPTIONS)"
    const val STR_WHEN_INDEX = "when (index)"
    const val STR_ARROW = " ->"
    const val STR_UNDERSCORE = "_"
    const val TEMPLATE_ASSIGN_L = " = %L"
    const val STR_MINUS_ONE_BREAK = "-1 -> break"
    const val STR_MINUS_TWO_ARROW = "-2 ->"
    const val STR_SKIP_VALUE = "reader.skipValue()"
    const val STR_END_OBJECT = "reader.endObject()"
    const val TEMPLATE_DESERIALIZE_T = "%T.deserialize(reader)"
    const val STR_NEXT_INT = "reader.nextInt()"
    const val STR_NEXT_BOOLEAN = "reader.nextBoolean()"
    const val STR_NEXT_LONG = "reader.nextLong()"
    const val STR_NEXT_DOUBLE = "reader.nextDouble()"
    const val STR_NEXT_FLOAT = "reader.nextFloat()"
    const val STR_SERIALIZERS_PKG = "com.ghost.serialization.serializers"
    const val STR_NEXT_STRING = "reader.nextString()"
    const val STR_NULL_CHECK_INT = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextInt()"
    const val STR_NULL_CHECK_LONG = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextLong()"
    const val STR_NULL_CHECK_DOUBLE = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextDouble()"
    const val STR_NULL_CHECK_FLOAT = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextFloat()"
    const val STR_NULL_CHECK_BOOLEAN = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextBoolean()"
    const val TEMPLATE_NULL_CHECK_L = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else %L"
    const val TEMPLATE_THROW_S = "reader.throwError(%S)"
    const val STR_REQ_FIELD_1 = "Required field '"
    const val STR_REQ_FIELD_2 = "' missing in JSON"
    const val STR_COMMA_SPACE = ", "
    const val STR_BANG_BANG = "!!"
    const val TEMPLATE_RETURN_T_PAREN = "return %T("
    const val STR_PAREN = ")"
    const val STR_EQ_SPACE = " = "
    const val TEMPLATE_VAL_RESULT = "val _result = %T("
    const val STR_OR = " || "
    const val STR_RETURN_RESULT_COPY = "return _result.copy("
    const val STR_COMMA = ","
    const val STR_EMPTY = ""
    const val STR_ELSE = "else"
    const val STR_RETURN_RESULT_FINAL = "return _result"
    const val STR_ERR_INVALID_ENUM_INDEX = "-1 -> reader.throwError(\"Invalid enum value\")"
    const val STR_ERR_UNEXPECTED_INDEX = "else -> throw GhostJsonException(\"Unexpected index: \$index\")"
    const val STR_FALLBACK_ANNOTATION = "GhostFallback"
    const val STR_ELSE_BRANCH = "else ->"
    const val STR_ENUM_SELECT_OPTIONS = "val index = reader.selectString(ENUM_OPTIONS)"
    const val STR_ENUM_WHEN = "return when (index)"
    const val TEMPLATE_ENUM_BRANCH = "%L -> %T.%L"
    const val STR_MASK_INIT = "var _mask%L = 0L"
    const val STR_CTX_CLASS = "DeserializationContext"
    const val STR_DECODE_CHUNK_PREFIX = "decodeChunk"
    const val STR_READER_VAR = "reader"
    const val STR_CTX_VAR = "ctx"
    const val STR_INDEX_VAR = "index"
    const val STR_WHEN_INDEX_PLAIN = "when (index)"
    const val STR_BIT_MASK_MIN_LONG = "Long.MIN_VALUE"
    const val TEMPLATE_BIT_MASK_LONG = "%LL"
    const val TEMPLATE_DECODE_RESILIENT = "reader.decodeResilient { %L }?.let"
    const val TEMPLATE_CTX_FIELD_ASSIGN = "ctx._%L = %L"
    const val TEMPLATE_CTX_FIELD_SET_IT = "ctx._%L = it"
    const val TEMPLATE_CTX_MASK_OR = "ctx._mask%L = ctx._mask%L or %L"
    const val STR_CTX_INIT = "val ctx = DeserializationContext()"
    const val TEMPLATE_CHUNK_CALL = "in %L..%L -> %L(reader, ctx, index)"
    const val TEMPLATE_IF_MASK_MISSING = "if ((ctx._mask%L and %L) == 0L)"
    const val STR_NULL_CHECK_1 = "if (reader.isNextNullValue()) { reader.consumeNull(); null } "
    const val STR_NULL_CHECK_2 = "else %T.deserialize(reader)"
    const val STR_MASK = "mask"
    const val STR_READ_LIST_TEMPLATE = "reader.readList { %L }"
    const val STR_READ_MAP_TEMPLATE = "reader.readMap({ reader.nextKey()!! }) { %L }"
    const val TEMPLATE_IF_MASK_ZERO_SIMPLE = "if ((_mask%L and %L) == 0L)"
    const val STR_MASK_BITWISE_OR = "_mask%L = _mask%L or %L"
    const val STR_IF_OPEN = "if ("
    const val TEMPLATE_IF_MASK_MATCH_BIT_F = "(ctx._mask%s and %s) != 0L"
    const val STR_CLOSE_PAREN_FLOW = ")"
    const val TEMPLATE_RESULT_FIELD_ASSIGN = "  %L = %L"
}
