package com.ghost.serialization.compiler

import com.squareup.kotlinpoet.ClassName

/**
 * Centralized constants for the deserialization code emitters and generators.
 *
 * Contains all string literals, templates, and identifiers used during code generation
 * to ensure consistency and eliminate magic strings across the emitter modules.
 */
internal object GhostEmitterConstants {
    const val STR_DESERIALIZE = "deserialize"
    const val STR_KDOC_DESERIALIZE = "Robust deserialization for [%T].\n"
    const val STR_NOTHING_TO_INLINE = "NOTHING_TO_INLINE"
    const val DEFAULT_CHUNK_SIZE = 200
    const val STR_READER = "reader"
    const val TEMPLATE_PEEK_TYPE = "val typeName = reader.peekStringField(%S) ?: reader.throwError(%S)"
    const val STR_MISSING_TYPE = "Missing discriminator field for sealed class"
    const val STR_WHEN_TYPENAME = "val result = when (typeName)"
    const val TEMPLATE_DESERIALIZE_BRANCH = "%S -> %T.deserialize(reader)"
    const val STR_UNKNOWN_TYPE = "else -> reader.throwError(\"Unknown type discriminator: \$typeName\")"
    const val STR_RETURN_RESULT = "return result"
    const val TEMPLATE_RETURN_CONSTRUCTOR = "return %T(%L)"
    const val STR_NULL = "null"
    const val STR_ZERO = "0"
    const val STR_ZERO_L = "0L"
    const val STR_ZERO_D = "0.0"
    const val STR_ZERO_F = "0.0f"
    const val STR_FALSE = "false"
    const val STR_VAR_UNDERSCORE = "var _"
    const val TEMPLATE_VAR_INIT = ": %T = %L"
    const val STR_BEGIN_OBJECT = "reader.beginObject()"
    const val STR_WHILE_TRUE = "while (true)"
    const val STR_SELECT_NAME_AND_CONSUME = "val index = reader.selectNameAndConsume(OPTIONS)"
    const val STR_SELECT_SUB_NAME = "val subIndex = reader.selectNameAndConsume(%L)"
    const val STR_WHEN_INDEX = "when (index)"
    const val STR_WHEN_SUB_INDEX = "when (subIndex)"
    const val STR_ARROW = " ->"
    const val STR_UNDERSCORE = "_"
    const val TEMPLATE_ASSIGN_L = " = %L"
    const val STR_MINUS_ONE_BREAK = "-1 -> break"
    const val STR_MINUS_TWO_ARROW = "-2 ->"
    const val STR_SKIP_VALUE = "reader.skipValue()"
    const val STR_END_OBJECT = "reader.endObject()"
    const val TEMPLATE_DESERIALIZE_T = "%T.deserialize(reader)"
    const val TEMPLATE_DESERIALIZE_L = "%L.deserialize(reader)"
    const val STR_NEXT_INT = "reader.nextInt()"
    const val STR_NEXT_BOOLEAN = "reader.nextBoolean()"
    const val STR_NEXT_LONG = "reader.nextLong()"
    const val STR_NEXT_DOUBLE = "reader.nextDouble()"
    const val STR_NEXT_FLOAT = "reader.nextFloat()"
    const val STR_SERIALIZERS_PKG = "com.ghost.serialization.serializers"
    const val STR_NEXT_STRING = "reader.nextString()"
    const val TEMPLATE_L_READER = "%T.%L(reader)"
    const val STR_NULL_CHECK_INT = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextInt()"
    const val STR_NULL_CHECK_LONG = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextLong()"
    const val STR_NULL_CHECK_DOUBLE = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextDouble()"
    const val STR_NULL_CHECK_FLOAT = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextFloat()"
    const val STR_NULL_CHECK_BOOLEAN = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else reader.nextBoolean()"
    const val TEMPLATE_NULL_CHECK_L = "if (reader.isNextNullValue()) { reader.consumeNull(); null } else %L"
    const val TEMPLATE_THROW_S = "reader.throwError(%S)"
    const val STR_REQ_FIELD_1 = "Required field '"
    const val STR_REQ_FIELD_2 = "' missing in JSON"
    const val STR_COMMA_SPACE = ", "
    const val STR_BANG_BANG = "!!"
    const val TEMPLATE_RETURN_T_PAREN = "return %T("
    const val STR_PAREN = ")"
    const val STR_EQ_SPACE = " = "
    const val TEMPLATE_VAL_RESULT = "val _result = %T("
    const val STR_OR = " || "
    const val STR_RETURN_RESULT_COPY = "return _result.copy("
    const val STR_COMMA = ","
    const val STR_EMPTY = ""
    const val STR_ELSE = "else"
    const val STR_RETURN_RESULT_FINAL = "return _result"
    const val STR_ERR_INVALID_ENUM_INDEX = "-1 -> reader.throwError(\"Invalid enum value\")"
    const val STR_ERR_UNEXPECTED_INDEX = "else -> throw GhostJsonException(\"Unexpected index: \$index\")"
    const val STR_FALLBACK_ANNOTATION = "GhostFallback"
    const val STR_ELSE_BRANCH = "else ->"
    const val STR_ENUM_SELECT_OPTIONS = "val index = reader.selectString(ENUM_OPTIONS)"
    const val STR_ENUM_WHEN = "return when (index)"
    const val TEMPLATE_ENUM_BRANCH = "%L -> %T.%L"
    const val STR_MASK_INIT = "var _mask%L = 0L"
    const val STR_CTX_CLASS = "DecodingContext"
    const val STR_DECODE_CHUNK_PREFIX = "decodeChunk"
    const val STR_SERIALIZE_CHUNK_PREFIX = "serializeChunk"
    const val STR_READER_VAR = "reader"
    const val STR_CTX_VAR = "ctx"
    const val STR_INDEX_VAR = "index"
    const val STR_WHEN_INDEX_PLAIN = "when (index)"
    const val STR_BIT_MASK_MIN_LONG = "Long.MIN_VALUE"
    const val TEMPLATE_DECODE_RESILIENT = "reader.decodeResilient { %L }?.let"
    const val TEMPLATE_CTX_FIELD_ASSIGN = "ctx._%L = %L"
    const val TEMPLATE_CTX_FIELD_SET_IT = "ctx._%L = it"
    const val TEMPLATE_CTX_MASK_OR = "ctx._mask%L = ctx._mask%L or %L"
    const val STR_CTX_INIT = "val ctx = DecodingContext()"
    const val TEMPLATE_CHUNK_CALL = "in %L..%L -> %L(reader, ctx, index)"
    const val TEMPLATE_IF_MASK_MISSING = "if ((ctx._mask%L and %L) == 0L)"
    const val STR_NULL_CHECK_1 = "if (reader.isNextNullValue()) { reader.consumeNull(); null } "
    const val STR_NULL_CHECK_2 = "else %T.deserialize(reader)"
    const val STR_MASK = "mask"
    const val STR_READ_LIST_TEMPLATE = "reader.readList { %L }"
    const val STR_READ_MAP_TEMPLATE = "reader.readMap({ reader.nextKey()!! }) { %L }"
    const val TEMPLATE_IF_MASK_ZERO_SIMPLE = "if ((_mask%L and %L) == 0L)"
    const val STR_MASK_BITWISE_OR = "_mask%L = _mask%L or %L"
    const val STR_IF_OPEN = "if ("
    const val TEMPLATE_IF_MASK_MATCH_BIT_F = "(ctx._mask%s and %s) != 0L"
    const val STR_CLOSE_PAREN_FLOW = ")"
    const val TEMPLATE_IF_MASK_NOT_MET = "if ((ctx._mask%L and %L) != %L)"
    const val TEMPLATE_RESULT_FIELD_ASSIGN = "  %L = %L"
    const val TEMPLATE_MASK_CHECK_MATCH = "(_mask%s and %s) != 0L"
    const val TEMPLATE_IF_MASK_NOT_MET_SIMPLE = "if ((_mask%L and %L) != %L)"
    const val STR_GHOST_PKG = "com.ghost.serialization"
    const val STR_CONTRACT_PKG = "com.ghost.serialization.contract"
    const val STR_GHOST_OBJ = "Ghost"
    const val STR_GHOST_SERIALIZER = "GhostSerializer"
    const val TEMPLATE_RESOLVE_SERIALIZER = "%T.getSerializer(%T::class)!!"
    val BYTE_STRING_CLASS = ClassName("okio", "ByteString")
    const val KOTLIN_STRING = "kotlin.String"
    const val DEFAULT_DISCRIMINATOR_KEY = "key"

    const val STR_WRITER_BEGIN_OBJ = "writer.beginObject()"
    const val STR_WRITER_NAME_TYPE_VAL = "writer.name(%S).value(%S)"
    const val STR_WRITER_WRITE_NAME_VAL = "writer.name(%L)"
    const val STR_WRITER_END_OBJ = "writer.endObject()"
    const val STR_WRITER_BEGIN_ARR = "writer.beginArray()"
    const val STR_WRITER_END_ARR = "writer.endArray()"
    const val STR_PARAM_WRITER = "writer"
    const val STR_PARAM_VALUE = "value"
    const val STR_OPTIONS_NAME = "OPTIONS"
    const val TEMPLATE_CHUNK_CALL_WRITER = "%N(writer, value)"
    const val STR_FUN_SERIALIZE = "serialize"
    const val STR_WHEN_VALUE = "when (value)"
    const val STR_SERIALIZER_SUFFIX = "Serializer"
    const val TEMPLATE_CHUNK_FUN_NAME = "%s%s_%s"
    const val TEMPLATE_DECODE_CHUNK_NAME = "%s%s"
    const val STR_IS_T_ARROW_T_SERIALIZE = "is %T -> %T.serialize(writer, value)"
    const val STR_VALUE_DOT = "value."
    const val STR_CTX_DOT = "ctx."
    const val STR_RESULT_DOT = "_result."
    const val STR_IF_ACCESSOR_NOT_NULL = "if (%L != null)"
    const val TEMPLATE_VAR_NAME = "_%s"
    const val TEMPLATE_RESULT_VAR = "_result.%s"
    const val TEMPLATE_MASK_VAR = "_mask%s"
    const val TEMPLATE_CTX_VAR = "ctx._%s"
    const val TEMPLATE_CTX_MASK_VAR = "ctx._mask%s"
    const val TEMPLATE_IF_MASK_RETURN = "if ((%s and %s) != 0L) %s else %s"
    const val TEMPLATE_WRAP_TYPE = "%s(%s)"
    const val STR_ANNOTATION_SERIALIZATION = "com.ghost.serialization.annotations.GhostSerialization"
    const val STR_GENERATED_PKG = "com.ghost.serialization.generated"
    const val STR_REGISTRY_PREFIX = "GhostModuleRegistry"
    const val STR_LOG_PREFIX = ">>> [GhostSerialization]"
    const val OPTION_MOSHI = "ghost.generateMoshiAdapters"
    const val OPTION_MODULE_NAME = "ghost.moduleName"
    const val STR_DEFAULT_NAME = "Default"
    const val STR_DASH = "-"
    const val STR_LOG_MOSHI_SKIPPED = " ghost.generateMoshiAdapters=false: Moshi JsonAdapter generation skipped. Binary footprint reduced to 1 class per model."
    const val STR_LOG_OPTIMIZED = " Successfully optimized: "
    const val STR_LOG_CRITICAL = " Critical error processing "
    const val STR_COLON_SPACE = ": "
    const val STR_REFLECT_PKG = "kotlin.reflect"
    const val STR_KCLASS = "KClass"
    const val STR_TYPE_T = "T"
    const val STR_COLLECTIONS_PKG = "kotlin.collections"
    const val STR_MAP = "Map"
    const val STR_FORMAT_S = "%S"
    const val STR_MAP_OF = "mapOf(\n"
    const val STR_MAP_ENTRY = "    %T::class to %T"
    const val STR_COMMA_NEWLINE = ",\n"
    const val STR_NEWLINE = "\n"
    const val STR_NEWLINE_PAREN = "\n)"
    const val STR_PAREN_CLOSE = ")"
    const val STR_PROP_SERIALIZERS_MAP = "serializersByClass"
    const val STR_CURLY_CLOSE = "}"
    const val STR_FUN_GET_SERIALIZER = "getSerializer"
    const val STR_PARAM_CLAZZ = "clazz"
    const val STR_UNCHECKED_CAST = "UNCHECKED_CAST"
    const val STR_GHOST_REGISTRY = "GhostRegistry"
    const val STR_FUN_PREWARM = "prewarm"
    const val STR_SERIALIZERS_SIZE = "serializersByClass.size"
    const val STR_FUN_REG_COUNT = "registeredCount"
    const val STR_FUN_GET_ALL_SERIALIZERS = "getAllSerializers"
    const val STR_RETURN_SERIALIZERS = "return serializersByClass"
    const val STR_KDOC_REGISTRY = "Generated Registry for GhostSerialization.\nUses a when-based getSerializer for cold-start-friendly class loading and a lazy map for getAllSerializers."
    const val STR_INSTANCE = "INSTANCE"
    const val STR_INIT_INSTANCE = "%T()"
    const val STR_META_INF_PROGUARD = "META-INF.proguard"
    const val STR_GHOST_SERIALIZATION_FILE = "ghost-serialization"
    const val STR_EXT_PRO = "pro"
    const val STR_LOG_PROGUARD_WARN = " Could not generate ProGuard rules: "
    const val STR_SERVICE_REGISTRY = "com.ghost.serialization.contract.GhostRegistry"
    const val STR_META_INF_SERVICES = "META-INF.services"
    const val STR_LOG_SERVICE_WARN = " Could not generate ServiceLoader file: "
    const val STR_LAZY_START = "lazy {\n"
    const val STR_LAZY = "lazy"
    const val STR_WHEN_CLAZZ_START = "return when (clazz) {\n"
    const val STR_WHEN_ENTRY = "    %T::class -> %T\n"
    const val STR_WHEN_ELSE_NULL = "    else -> null\n"
    const val STR_WHEN_CLOSE_CAST = "} as %T\n"
    const val PKG_PARSER = "com.ghost.serialization.parser"
    const val STR_IGNORE = "ignore"
    const val STR_IGNORE_CALL = "%L.ignore()"
    const val STR_RETURN_L = "return %L"

    const val TEMPLATE_PROGUARD_KEEP = """
        # GhostSerialization Robust Keep Rules
        -keep class %s.%s {
            public static ** INSTANCE;
            public *** getSerializer(...);
        }
        -keep class * implements com.ghost.serialization.contract.GhostSerializer {
            *;
        }
    """
    const val STR_DOT = "."
    const val STR_QUOTE = "\""
    const val STR_COLON = ":"
    const val STR_BACKTICK = "`"
    const val STR_T_SERIALIZE_WRITER_ACC = "%T.serialize(writer, %L)"
    const val STR_FOR_ITEM_IN_ACC = "for (item in %L)"
    const val STR_WRITER_VALUE_ITEM = "writer.value(item)"
    const val STR_FOR_MAP_IN_ACC = "for ((mapKey, mapVal) in %L)"
    const val STR_WRITER_NAME_MAPKEY = "writer.name(mapKey)"
    const val STR_WRITER_VALUE_MAPVAL = "writer.value(mapVal)"
    const val STR_ENUM_MEMBER_VAL = "%T.%L -> writer.value(%S)"
    const val STR_WRITER_VAL_ENUM_NAME = "writer.value(value.name)"
    const val K_INT = "kotlin.Int"
    const val K_LONG = "kotlin.Long"
    const val K_STRING = "kotlin.String"
    const val K_BOOLEAN = "kotlin.Boolean"
    const val K_DOUBLE = "kotlin.Double"
    const val K_FLOAT = "kotlin.Float"
    const val K_BYTE = "kotlin.Byte"
    const val K_SHORT = "kotlin.Short"
    const val K_CHAR = "kotlin.Char"
    const val K_UNIT = "kotlin.Unit"
    const val K_ANY = "kotlin.Any"
    const val STR_KOTLIN_PREFIX = "kotlin."
    const val STR_JAVA_PREFIX = "java."
    const val STR_WRITER_WRITE_FIRST = "writer.writeFirstField(%L, value.%L)"
    const val STR_WRITER_WRITE_NAME_RAW = "writer.writeNameRaw(%L)"
    const val STR_WRITER_WRITE_FIELD_COMMA = "writer.writeFieldWithComma(%L, value.%L)"
    const val STR_WRITER_WRITE_NAME_RAW_COMMA = "writer.writeNameRawWithComma(%L)"
    const val STR_WRITER_WRITE_FIELD = "writer.writeField(%L, value.%L)"
    const val STR_H_FIRST = "STR_H_F_"
    const val STR_H_COMMA = "STR_H_C_"
    const val STR_H_STD = "STR_H_S_"
    const val STR_H_VAL_PREFIX = "H_"
    const val STR_SERIALIZE_CALL = "%L.serialize(writer, %L)"
    const val STR_WRITER_VAL_L = "writer.value(%L)"
    const val STR_WRITER_VAL_FLOAT = "writer.value(%L.toDouble())"
    const val STR_WRITE_FIELD = "writer.writeField(%L, %L)"
    const val STR_WRITE_NAME_RAW = "writer.name(%L)"
    const val STR_WRITE_NAME_RAW_NULL = "writer.writeNameRaw(%L).nullValue()"
    const val TEMPLATE_IF_NOT_NULL = "if (%L != null)"
    const val STR_CUSTOM_ENCODER_CALL = "%T.%L(writer, %L)"
    const val STR_VAR_ITEM = "item"
    const val STR_VAR_MAP_VAL = "mapVal"
    const val STR_CONTEXTUAL_PREFIX = "contextual_"
    const val TEMPLATE_H_FIRST_INIT = "%N.writerFirstHeaders[0]"
    const val TEMPLATE_H_COMMA_INIT = "%N.writerHeadersWithComma[%L]"
    const val TEMPLATE_H_STD_INIT = "%N.writerHeaders[%L]"
    
    // Analyzer Constants
    const val STR_ERR_CLASS_1 = "GhostSerialization: @GhostSerialization can only be applied to 'data class', 'sealed class', 'value class' or 'enum class'. "
    const val STR_ERR_CLASS_2 = "Class '"
    const val STR_ERR_CLASS_3 = "' is not supported."
    const val STR_ERR_PRIV_1 = "GhostSerialization: Properties in @GhostSerialization classes cannot be private. "
    const val STR_ERR_PRIV_2 = "Please remove 'private' modifier from properties in '"
    const val STR_ERR_PRIV_3 = "'."
    const val STR_ERR_DUP_1 = "GhostSerialization: Duplicate JSON name '"
    const val STR_ERR_DUP_2 = "' found in class '"
    const val STR_ERR_DUP_3 = "'. "
    const val STR_ERR_DUP_4 = "Problematic properties: "
    const val STR_ERR_MAP_1 = "GhostSerialization: Map key must be a String in property '"
    const val STR_ERR_MAP_2 = "'. "
    const val STR_ERR_MAP_3 = "JSON only supports string-keyed objects."
    const val STR_KOTLIN_DOT = "kotlin."
    const val STR_TYPE_INT_ARRAY = "kotlin.IntArray"
    const val STR_TYPE_LONG_ARRAY = "kotlin.LongArray"
    const val STR_TYPE_FLOAT_ARRAY = "kotlin.FloatArray"
    const val STR_TYPE_DOUBLE_ARRAY = "kotlin.DoubleArray"
    const val STR_TYPE_BOOLEAN_ARRAY = "kotlin.BooleanArray"
    const val GHOST_IGNORE = "GhostIgnore"
    const val GHOST_NAME = "GhostName"
    const val SERIAL_NAME = "SerialName"
    const val GHOST_SERIALIZATION = "GhostSerialization"
    const val NAME_ARG = "name"
    const val LIST_QUALIFIED = "kotlin.collections.List"
    const val MAP_QUALIFIED = "kotlin.collections.Map"
    const val STRING_QUALIFIED = "kotlin.String"
    const val STR_VALUE_ARG = "value"
    const val STR_SERIAL_NAME_SUFFIX = "SerialName"
    const val GHOST_RESILIENT = "GhostResilient"
    const val GHOST_DECODER = "GhostDecoder"
    const val GHOST_ENCODER = "GhostEncoder"
    const val PROVIDER_ARG = "provider"
    const val FUNCTION_NAME_ARG = "functionName"
    const val GHOST_FLATTEN = "GhostFlatten"
    const val GHOST_WRAP = "GhostWrap"
    const val PATH_ARG = "path"
    const val ORDINAL = "ordinal"
    const val NAME = "name"

    // Generator-specific
    const val PKG_WRITER = "com.ghost.serialization.writer"
    const val PKG_CONTRACT = "com.ghost.serialization.contract"
    const val PKG_EXCEPTION = "com.ghost.serialization.exception"
    const val PKG_GHOST = "com.ghost.serialization"
    const val OKIO_PACKAGE = "okio"
    const val DECODE_RESILIENT = "decodeResilient"
    const val STR_GHOST_JSON_WRITER = "GhostJsonWriter"
    const val STR_GHOST_JSON_FLAT_WRITER = "GhostJsonFlatWriter"
    const val STR_GHOST_JSON_READER = "GhostJsonReader"
    const val STR_BEGIN_ARRAY = "beginArray"
    const val STR_END_ARRAY = "endArray"
    const val STR_HAS_NEXT = "hasNext"
    const val STR_IS_NEXT_NULL_VALUE = "isNextNullValue"
    const val STR_CONSUME_NULL = "consumeNull"
    const val STR_READ_LIST = "readList"
    const val STR_READ_MAP = "readMap"
    const val STR_NEXT_KEY = "nextKey"
    const val STR_SELECT_STRING = "selectString"
    const val STR_CONSUME_KEY_SEPARATOR = "consumeKeySeparator"
    const val STR_CONSUME_ARRAY_SEPARATOR = "consumeArraySeparator"
    const val STR_PEEK_STRING_FIELD = "peekStringField"
    const val STR_GHOST_JSON_EXCEPTION = "GhostJsonException"
    const val STR_BYTESTRING_IMPORT = "ByteString.Companion.encodeUtf8"
    const val STR_OPTIONS_OF = "%T.of(\n"
    const val STR_OPTIONS_OF_SEEDS = "%T.of(%L, %L,\n"
    const val STR_KDOC_HIGH_PERF = "High-performance serializer for [%T].\n"
    const val STR_KDOC_GENERATED = "Generated by GhostSerialization. Do not modify manually.\n"
    const val STR_OPTIONS = "OPTIONS"
    const val STR_OPTIONS_PREFIX = "OPTIONS_"
    const val STR_OPTIONS_CLASS = "JsonReaderOptions"
    const val STR_ENUM_OPTIONS = "ENUM_OPTIONS"
    const val STR_WARM_UP = "warmUp"
    const val STR_EMPTY_OBJ = "{}"
    val STR_WARM_UP_BODY = """
            |try {
            |  val reader = %T(%S.encodeToByteArray())
            |  deserialize(reader).ignore()
            |} catch (e: Exception) {}
        """.trimMargin()
    const val MARKER = "%S"
    const val ANNOTATION_GHOST_SERIALIZATION = "GhostSerialization"
    const val ARG_DISCRIMINATOR = "discriminator"
    const val STR_DEFAULT_DISCRIMINATOR = "type"
    const val ARG_NAME = "name"
    const val PKG_KOTLIN = "kotlin"
    const val STR_OPT_IN = "OptIn"
    const val STR_INTERNAL_GHOST_API = "InternalGhostApi"
    const val STR_TYPE_NAME_PROP = "typeName"
    const val STR_SUPPRESS_FORMAT = "$MARKER, $MARKER, $MARKER, $MARKER, $MARKER, $MARKER, $MARKER, $MARKER"
    const val LINT_UNUSED_VARIABLE = "UNUSED_VARIABLE"
    const val LINT_UNUSED_EXPRESSION = "UNUSED_EXPRESSION"
    const val LINT_UNCHECKED_CAST = "UNCHECKED_CAST"
    const val LINT_USELESS_CAST = "USELESS_CAST"
    const val LINT_UNNECESSARY_NOT_NULL_ASSERTION = "UNNECESSARY_NOT_NULL_ASSERTION"
    const val LINT_UNUSED = "unused"
    const val LINT_NAME_SHADOWING = "NAME_SHADOWING"
    const val LINT_UNUSED_RESULT = "UNUSED_RESULT"
    const val HASH_MULTIPLIER_START = 31
    const val HASH_MULTIPLIER_LIMIT = 2000
    const val HASH_MULTIPLIER_STEP = 2
    const val HASH_SHIFT_LIMIT = 16
    const val HASH_TABLE_SIZE = 1024
    const val HASH_MASK = 1023
    const val BYTE_MASK = 0xFF
    const val BIT_SHIFT_8 = 8
    const val BIT_SHIFT_16 = 16
    const val BIT_SHIFT_24 = 24
    const val MARKER_CLASS = "%T::class"
    const val STR_WRITER_NULL_VAL = "writer.nullValue()"
}
