package com.ghost.serialization.compiler

import com.google.devtools.ksp.symbol.KSClassDeclaration
import com.squareup.kotlinpoet.*
import com.squareup.kotlinpoet.ParameterizedTypeName.Companion.parameterizedBy
import com.squareup.kotlinpoet.ksp.toClassName

internal class GhostCodeGenerator(
    private val classDeclaration: KSClassDeclaration,
    private val properties: List<GhostPropertyModel>
) {
    private val isSealed = classDeclaration.modifiers.contains(com.google.devtools.ksp.symbol.Modifier.SEALED)
    private val isValue = classDeclaration.modifiers.contains(com.google.devtools.ksp.symbol.Modifier.VALUE) || 
                          classDeclaration.modifiers.contains(com.google.devtools.ksp.symbol.Modifier.INLINE)
    private val sealedSubclasses = if (isSealed) classDeclaration.getSealedSubclasses().toList() else emptyList()
    private val packageName = classDeclaration.packageName.asString()
    private val baseClassName = classDeclaration.simpleName.asString()
    private val generatedClassName = "Ghost$baseClassName"
    private val ghostClassName = ClassName(packageName, generatedClassName)
    private val originalClassName = classDeclaration.toClassName()
    private val discriminator = if (!isSealed && !isValue && classDeclaration.parentDeclaration is KSClassDeclaration && 
                                   (classDeclaration.parentDeclaration as KSClassDeclaration).modifiers.contains(com.google.devtools.ksp.symbol.Modifier.SEALED)) {
        classDeclaration.simpleName.asString()
    } else null

    private val serializerInterface = ClassName(PKG_CONTRACT, "GhostSerializer")
    private val writerClass = ClassName(PKG_WRITER, "GhostJsonWriter")
    private val readerClass = ClassName(PKG_PARSER, "GhostJsonReader")
    private val bufferedSink = ClassName(OKIO_PACKAGE, "BufferedSink")
    private val bufferedSource = ClassName(OKIO_PACKAGE, "BufferedSource")

    fun createSpec(): FileSpec {
        val serializerName = "${baseClassName}Serializer"
        return FileSpec.builder(packageName, serializerName)
            .addImport(PKG_PARSER, "isNextNullValue", "consumeNull", "skipValue", "readList",
                "nextKey", "nextInt", "nextLong", "nextDouble", "selectName",
                "consumeKeySeparator", "consumeArraySeparator", "nextFloat", "peekStringField")
            .addImport(PKG_EXCEPTION, "GhostJsonException")
            .addImport("okio.ByteString.Companion", "encodeUtf8")
            .addType(buildSerializerObject())
            .build()
    }

    private fun buildSerializerObject(): TypeSpec {
        val optionsBuilder = CodeBlock.builder()
            .add("%T.Options.of(\n", readerClass)
            .indent()

        properties.forEachIndexed { index, prop ->
            val comma = if (index < properties.size - 1) "," else ""
            optionsBuilder.add("%S$comma\n", prop.jsonName)
        }
        optionsBuilder.unindent().add(")")

        val serializeEmitter = SerializeCodeEmitter(
            properties, originalClassName, writerClass, bufferedSink, isSealed, isValue, sealedSubclasses, discriminator
        )
        val deserializeEmitter = DeserializeCodeEmitter(
            properties, originalClassName, readerClass, bufferedSource, isSealed, isValue, sealedSubclasses
        )

        val serializerName = "${baseClassName}Serializer"
        val namesArrayBuilder = CodeBlock.builder().add("arrayOf(\n").indent()
        properties.forEachIndexed { index, prop ->
            val comma = if (index < properties.size - 1) "," else ""
            namesArrayBuilder.add("%S.encodeUtf8()$comma\n", prop.jsonName)
        }
        namesArrayBuilder.unindent().add(")")

        return TypeSpec.objectBuilder(serializerName)
            .addKdoc("High-performance serializer for [%T].\n", originalClassName)
            .addKdoc("Generated by GhostSerialization. Do not modify manually.\n")
            .addSuperinterface(serializerInterface.parameterizedBy(originalClassName))
            .addProperty(
                PropertySpec.builder("OPTIONS", readerClass.nestedClass("Options"))
                    .addModifiers(KModifier.PRIVATE)
                    .initializer(optionsBuilder.build())
                    .build()
            )
            .addFunction(serializeEmitter.build())
            .addFunction(deserializeEmitter.build())
            .build()
    }

    companion object {
        private const val PKG_PARSER     = "com.ghost.serialization.core.parser"
        private const val PKG_WRITER     = "com.ghost.serialization.core.writer"
        private const val PKG_CONTRACT   = "com.ghost.serialization.core.contract"
        private const val PKG_EXCEPTION  = "com.ghost.serialization.core.exception"
        private const val PKG_SERIALIZERS = "com.ghost.serialization.serializers"
        private const val OKIO_PACKAGE   = "okio"
    }
}