package com.ghost.serialization.compiler

internal object GhostGeneratorConstants {
    const val PKG_PARSER = "com.ghost.serialization.parser"
    const val PKG_WRITER = "com.ghost.serialization.writer"
    const val PKG_CONTRACT = "com.ghost.serialization.contract"
    const val PKG_EXCEPTION = "com.ghost.serialization.exception"
    const val PKG_GHOST = "com.ghost.serialization"
    const val OKIO_PACKAGE = "okio"
    const val DECODE_RESILIENT = "decodeResilient"
    const val STR_GHOST_SERIALIZER = "GhostSerializer"
    const val STR_GHOST_JSON_WRITER = "GhostJsonWriter"
    const val STR_GHOST_JSON_FLAT_WRITER = "GhostJsonFlatWriter"
    const val STR_GHOST_JSON_READER = "GhostJsonReader"
    const val STR_BEGIN_OBJECT = "beginObject"
    const val STR_END_OBJECT = "endObject"
    const val STR_BEGIN_ARRAY = "beginArray"
    const val STR_END_ARRAY = "endArray"
    const val STR_HAS_NEXT = "hasNext"
    const val STR_IS_NEXT_NULL_VALUE = "isNextNullValue"
    const val STR_CONSUME_NULL = "consumeNull"
    const val STR_SKIP_VALUE = "skipValue"
    const val STR_READ_LIST = "readList"
    const val STR_READ_MAP = "readMap"
    const val STR_NEXT_KEY = "nextKey"
    const val STR_NEXT_INT = "nextInt"
    const val STR_NEXT_LONG = "nextLong"
    const val STR_NEXT_DOUBLE = "nextDouble"
    const val STR_NEXT_STRING = "nextString"
    const val STR_NEXT_BOOLEAN = "nextBoolean"
    const val STR_SELECT_NAME_AND_CONSUME = "selectNameAndConsume"
    const val STR_SELECT_STRING = "selectString"
    const val STR_CONSUME_KEY_SEPARATOR = "consumeKeySeparator"
    const val STR_CONSUME_ARRAY_SEPARATOR = "consumeArraySeparator"
    const val STR_NEXT_FLOAT = "nextFloat"
    const val STR_PEEK_STRING_FIELD = "peekStringField"
    const val STR_IGNORE = "ignore"
    const val STR_GHOST_JSON_EXCEPTION = "GhostJsonException"
    const val STR_BYTESTRING_IMPORT = "ByteString.Companion.encodeUtf8"
    const val STR_OPTIONS_OF = "%T.of(\n"
    const val STR_OPTIONS_OF_SEEDS = "%T.of(%L, %L,\n"
    const val STR_COMMA = ","
    const val STR_EMPTY = ""
    const val STR_PAREN_CLOSE = ")"
    const val STR_KDOC_HIGH_PERF = "High-performance serializer for [%T].\n"
    const val STR_KDOC_GENERATED =
        "Generated by GhostSerialization. Do not modify manually.\n"
    const val STR_OPTIONS = "OPTIONS"
    const val STR_OPTIONS_CLASS = "JsonReaderOptions"
    const val STR_ENUM_OPTIONS = "ENUM_OPTIONS"
    const val STR_WARM_UP = "warmUp"
    val STR_WARM_UP_BODY = """
            |try {
            |  val reader = %T("{}".encodeToByteArray())
            |  deserialize(reader).ignore()
            |} catch (e: Exception) {}
        """.trimMargin()
    const val MARKER = "%S"

    const val ANNOTATION_GHOST_SERIALIZATION = "GhostSerialization"
    const val ARG_DISCRIMINATOR = "discriminator"
    const val STR_DEFAULT_DISCRIMINATOR = "type"
    const val ARG_NAME = "name"
    const val PKG_KOTLIN = "kotlin"
    const val STR_OPT_IN = "OptIn"
    const val STR_INTERNAL_GHOST_API = "InternalGhostApi"
    const val STR_TYPE_NAME_PROP = "typeName"
    const val STR_UNDERSCORE = "_"
    const val STR_SUPPRESS_FORMAT =
        "$MARKER, $MARKER, $MARKER, $MARKER, $MARKER, $MARKER, $MARKER, $MARKER"
    const val LINT_UNUSED_VARIABLE = "UNUSED_VARIABLE"
    const val LINT_UNUSED_EXPRESSION = "UNUSED_EXPRESSION"
    const val LINT_UNCHECKED_CAST = "UNCHECKED_CAST"
    const val LINT_USELESS_CAST = "USELESS_CAST"
    const val LINT_UNNECESSARY_NOT_NULL_ASSERTION = "UNNECESSARY_NOT_NULL_ASSERTION"
    const val LINT_UNUSED = "unused"
    const val LINT_NAME_SHADOWING = "NAME_SHADOWING"
    const val LINT_UNUSED_RESULT = "UNUSED_RESULT"
    const val HASH_MULTIPLIER_START = 31
    const val HASH_MULTIPLIER_LIMIT = 2000
    const val HASH_MULTIPLIER_STEP = 2
    const val HASH_SHIFT_LIMIT = 16
    const val HASH_TABLE_SIZE = 1024
    const val HASH_MASK = 1023
    const val BYTE_MASK = 0xFF
    const val BIT_SHIFT_8 = 8
    const val BIT_SHIFT_16 = 16
    const val BIT_SHIFT_24 = 24
    const val STR_SERIALIZER_SUFFIX = "Serializer"
    const val STR_FORMAT_S = "%S"
    const val STR_NEWLINE = "\n"
}