package com.ghost.serialization.contract

import com.ghost.serialization.parser.bytes.GhostJsonFlatReader
import com.ghost.serialization.parser.streaming.GhostJsonReader
import com.ghost.serialization.parser.strings.GhostJsonStringReader
import com.ghost.serialization.writer.bytes.GhostJsonWriter
import com.ghost.serialization.writer.strings.GhostJsonStringWriter
import okio.BufferedSink
import okio.BufferedSource

/**
 * Base contract for high-performance JSON serializers, typically generated by the Ghost KSP
 * compiler plugin for reflection-free serialization/deserialization.
 *
 * [GhostJsonReader] (streaming) and [GhostJsonFlatReader] (in-memory) stay separate rather than
 * unified — costs real throughput on array-heavy payloads otherwise.
 *
 * [isResilient]: skip vs. throw on malformed collection items. [isProto]: proto3 canonical JSON
 * mapping — `BINARY`-retained, so runtime dispatch (e.g. Spring's `HttpMessageConverter`) checks
 * this instead of the annotation. [warmUp]: optional JIT/ART warm-up.
 */
interface GhostSerializer<T> {

    val typeName: String

    val isResilient: Boolean

    val isProto: Boolean

    fun deserialize(source: BufferedSource): T

    fun deserialize(reader: GhostJsonReader): T

    fun deserialize(reader: GhostJsonFlatReader): T

    fun deserialize(reader: GhostJsonStringReader): T

    fun serialize(sink: BufferedSink, value: T)

    fun serialize(writer: GhostJsonWriter, value: T)

    fun serialize(writer: GhostJsonStringWriter, value: T)

    fun warmUp()
}
