package com.ghost.serialization.contract

import com.ghost.serialization.InternalGhostApi
import com.ghost.serialization.ghostInternalEncodeAndDrainTo
import okio.BufferedSink
import okio.BufferedSource
import com.ghost.serialization.parser.GhostJsonReader
import com.ghost.serialization.parser.GhostJsonFlatReader
import com.ghost.serialization.writer.GhostJsonFlatWriter
import com.ghost.serialization.writer.GhostJsonWriter

/**
 * Base contract for high-performance JSON serializers.
 *
 * Implementations are typically generated by the Ghost KSP compiler plugin
 * to provide reflection-free serialization and deserialization.
 *
 * # Two-writer design
 *
 * Implementations must provide *two* `serialize(writer, value)` overloads —
 * one for [GhostJsonWriter] (streaming I/O over [okio.BufferedSink]) and one
 * for [GhostJsonFlatWriter] (in-memory growing [ByteArray]). Both are
 * `final` concrete classes, so each overload sees a known receiver and the
 * compiler/JIT can inline every byte-write fully. KSP-generated serializers
 * emit both with an identical body that differs only in parameter type.
 *
 * Handwritten serializers must do the same. Because the public API of both
 * writers is identical (same method names and signatures, only differing in
 * the `this` type), the body can usually be copy-pasted verbatim.
 */
@OptIn(InternalGhostApi::class)
interface GhostSerializer<T> {

    /** The unique name of the model in the Ghost registry. */
    val typeName: String

    /**
     * Whether this serializer supports resilient parsing (skipping malformed items
     * when used in collections).
     */
    val isResilient: Boolean get() = false

    /**
     * Serializes [value] into the provided [sink] using the fast in-memory
     * [GhostJsonFlatWriter] and a single bulk drain. See `Ghost.serialize`
     * for the full rationale.
     */
    fun serialize(sink: BufferedSink, value: T) {
        ghostInternalEncodeAndDrainTo(sink) { writer ->
            serialize(writer, value)
        }
    }

    /**
     * Serializes [value] using the streaming [writer] (segmented [okio.Buffer]
     * under the hood). Used by `Ghost.serialize(sink, value)`.
     */
    fun serialize(writer: GhostJsonWriter, value: T)

    /**
     * Serializes [value] using the in-memory [writer] (contiguous
     * [com.ghost.serialization.writer.FlatByteArrayWriter] under the hood).
     * Used by `Ghost.encodeToString` / `Ghost.encodeToBytes` to bypass Okio
     * segment overhead on the synchronous in-memory encode path.
     */
    fun serialize(writer: GhostJsonFlatWriter, value: T)

    /** Deserializes a new instance of [T] from the [source]. */
    fun deserialize(source: BufferedSource): T {
        val reader = GhostJsonFlatReader(source.readByteArray())
        return deserialize(reader)
    }

    /** Deserializes a new instance of [T] using a specialized streaming [reader]. */
    fun deserialize(reader: GhostJsonReader): T

    /** Deserializes a new instance of [T] using a specialized flat in-memory [reader]. */
    fun deserialize(reader: GhostJsonFlatReader): T {
        val temp = GhostJsonReader(reader.rawData).also { 
            it.position = reader.position 
            it.limit = reader.limit
        }
        val result = deserialize(temp)
        reader.position = temp.position
        reader.nextTokenByte = -1
        return result
    }

    /**
     * Optional warm-up cycle to trigger JIT (Just-In-Time) or ART optimization
     * for critical parsing paths.
     */
    fun warmUp() {}
}
