/**
 * Generated by Ghost Serialization (v1.1.7)
 * DO NOT EDIT MANUALLY.
 */

import type * as GhostWasm from "ghost-serialization-wasm";

export interface GhostModels {
    BridgeModel: import("../ghost-models/BridgeModel").BridgeModel;
}

type GhostEngine = typeof GhostWasm;

interface GhostInstantiateResult {
    instance: WebAssembly.Instance;
    exports: GhostEngine;
}

interface GhostUninstantiatedModule {
    instantiate(imports?: WebAssembly.Imports, runInitializer?: boolean): Promise<GhostInstantiateResult>;
}

let _engine: GhostEngine | null = null;

async function getGhostEngine(): Promise<GhostEngine> {
    if (_engine) return _engine;
    const mod = (await import("../../node_modules/ghost-serialization-wasm/ghost-serialization-wasm.uninstantiated.mjs")) as GhostUninstantiatedModule;
    const { exports } = await mod.instantiate();
    exports.ghostPrewarm();
    _engine = exports;
    return _engine;
}

export async function ensureGhostReady(): Promise<void> {
    await getGhostEngine();
}

export async function deserializeModel<K extends keyof GhostModels>(json: string, type: K): Promise<GhostModels[K]> {
    const wasm = await getGhostEngine();
    const result = wasm.ghostDeserialize(json, type as string);
    if (!result) throw new Error(`[Ghost] Failed to deserialize "${type}".`);
    return JSON.parse(result) as GhostModels[K];
}

export function deserializeModelSync<K extends keyof GhostModels>(json: string, type: K): GhostModels[K] {
    if (!_engine) throw new Error("[Ghost] Engine not ready. Await ensureGhostReady() before calling deserializeModelSync.");
    const result = _engine.ghostDeserialize(json, type as string);
    if (!result) throw new Error(`[Ghost] Failed to deserialize "${type}".`);
    return JSON.parse(result) as GhostModels[K];
}
