package com.ghost.serialization.core.contract

import okio.BufferedSink
import okio.BufferedSource
import com.ghost.serialization.core.parser.GhostJsonReader
import com.ghost.serialization.core.writer.GhostJsonWriter

/**
 * Base contract for high-performance JSON serializers.
 * 
 * Implementations are typically generated by the Ghost KSP compiler plugin
 * to provide reflection-free serialization and deserialization.
 */
interface GhostSerializer<T> {
    /** The unique name of the model in the Ghost registry. */
    val typeName: String


    /** Serializes [value] directly into the provided [sink]. */
    fun serialize(sink: BufferedSink, value: T) {
        val writer = GhostJsonWriter(sink)
        serialize(writer, value)
    }

    /** Serializes [value] using a specialized [writer]. */
    fun serialize(writer: GhostJsonWriter, value: T)
    
    /** Deserializes a new instance of [T] from the [source]. */
    fun deserialize(source: BufferedSource): T = deserialize(GhostJsonReader(source))

    /** Deserializes a new instance of [T] using a specialized [reader]. */
    fun deserialize(reader: GhostJsonReader): T

    /**
     * Optional warm-up cycle to trigger JIT (Just-In-Time) or ART optimization
     * for critical parsing paths.
     */
    fun warmUp() {}
}