package com.ghost.serialization

import kotlin.js.JsExport
import kotlin.js.JsName
import kotlin.js.ExperimentalJsExport
import com.ghost.serialization.core.contract.GhostRegistry
import com.ghost.serialization.core.contract.GhostSerializer
import com.ghost.serialization.core.parser.GhostJsonReader
import com.ghost.serialization.generated.GhostAutoRegistry
import com.ghost.serialization.generated.GhostJsRegistryInitializer

/**
 * JS/Wasm Bridge for Ghost Serialization.
 * Provides a high-performance entry point for JavaScript.
 */
@OptIn(ExperimentalJsExport::class)
@JsExport
@JsName("ghostPrewarm")
fun ghostPrewarm() {
    // 1. Register KSP-generated serializers (commonMain, all platforms)
    try {
        GhostAutoRegistry.registerAll()
    } catch (_: Exception) { /* Fallback for non-generated environments */ }
    // 2. Register JS object builders (wasmJsMain only, generated by ghost-transpiler)
    try {
        GhostJsRegistryInitializer.register()
    } catch (e: Exception) { 
        println(">>> [Ghost] CRITICAL: GhostJsRegistryInitializer failed: ${e.message}")
        e.printStackTrace()
    }
    Ghost.prewarm()
}

@OptIn(ExperimentalJsExport::class)
@JsExport
@JsName("ghostSerialize")
fun ghostSerialize(value: String): String {
    return Ghost.serialize(value)
}

/**
 * Since KClass is not available in JS, we use this bridge.
 * To support Wasm, we return a String (JSON) that can be parsed in JS.
 * This ensures the export is visible and functional.
 */
@OptIn(ExperimentalJsExport::class)
@JsExport
@JsName("ghostDeserialize")
fun ghostDeserialize(json: String, typeName: String): String? {
    return try {
        val serializer = Ghost.getSerializerByName(typeName) ?: run {
            println(">>> [Ghost] CRITICAL: Serializer not found for type: $typeName")
            println(">>> [Ghost] HINT: Ensure you ran the sync tool and the model is annotated with @GhostSerialization.")
            return null
        }
        val reader = GhostJsonReader(json.encodeToByteArray())
        val result = serializer.deserialize(reader) ?: return null
        
        Ghost.serialize(result)
    } catch (_: Exception) {
        null
    }
}

@OptIn(ExperimentalJsExport::class)
@JsExport
@JsName("ghostDeserializeBytes")
fun ghostDeserializeBytes(bytes: JsAny, typeName: String): String? {
    return try {
        val serializer = Ghost.getSerializerByName(typeName) ?: return null
        val reader = GhostJsonReader(jsToByteArray(bytes))
        val result = serializer.deserialize(reader) ?: return null
        Ghost.serialize(result)
    } catch (_: Exception) {
        null
    }
}

@OptIn(ExperimentalJsExport::class)
@JsExport
@JsName("ghostDeserializeBytesJs")
@Suppress("UNCHECKED_CAST")
fun ghostDeserializeBytesJs(bytes: JsAny, typeName: String): JsAny? {
    return try {
        val serializer = Ghost.getSerializerByName(typeName) ?: return null
        val reader = GhostJsonReader(jsToByteArray(bytes))
        val result = (serializer as GhostSerializer<Any>).deserialize(reader) ?: return null
        GhostJsObjectRegistry.build(typeName, result)
    } catch (_: Throwable) {
        null
    }
}

@OptIn(ExperimentalJsExport::class)
@JsExport
@JsName("ghostDeserializeJs")
@Suppress("UNCHECKED_CAST")
fun ghostDeserializeJs(json: String, typeName: String): JsAny? {
    return try {
        val serializer = Ghost.getSerializerByName(typeName) ?: return null
        val reader = GhostJsonReader(json.encodeToByteArray())
        val result = (serializer as GhostSerializer<Any>).deserialize(reader) ?: return null
        GhostJsObjectRegistry.build(typeName, result)
    } catch (_: Throwable) {
        null
    }
}
