package com.ghost.playground.features

import com.ghost.playground.ui.icons.PlaygroundIconKind

object SpeedPillars {
    val all: List<SpeedPillar> = listOf(
        SpeedPillar(
            PlaygroundIconKind.Bolt, "Generated serializers", "Serializers generados",
            "KSP walks your annotated data class at compile time and emits a dedicated Kotlin file with a monomorphic encode(value) and decode(reader) function for that exact type — direct field reads/writes and a real constructor call, not a generic \"visit each property\" loop.",
            "KSP recorre tu data class anotada en compile time y emite un archivo Kotlin dedicado con un encode(value) y decode(reader) monomórficos para ese tipo exacto — reads/writes directos a los campos y una llamada real al constructor, no un loop genérico de \"visitar cada propiedad\".",
            "Because the generated function only ever handles one concrete type, the JIT (or AOT compiler on Native/iOS) can inline it, keep everything on the stack, and avoid the megamorphic call sites that show up when one adapter method serves every type in your app.",
            "Como la función generada solo maneja un tipo concreto, el JIT (o el compilador AOT en Native/iOS) puede inlinearla, mantener todo en el stack, y evitar los call sites megamórficos que aparecen cuando un solo método adapter sirve a todos los tipos de la app.",
            "Gson resolves a TypeAdapter via reflection and caches it, but still walks Field objects and boxes primitives on every call. Moshi and kotlinx.serialization generate code too, but route every call through a KSerializer/JsonAdapter interface — one virtual dispatch per field that Ghost's direct calls skip entirely.",
            "Gson resuelve un TypeAdapter por reflexión y lo cachea, pero igual recorre objetos Field y boxea primitivos en cada llamada. Moshi y kotlinx.serialization también generan código, pero enrutan cada llamada por una interfaz KSerializer/JsonAdapter — un dispatch virtual por campo que las llamadas directas de Ghost se saltan por completo.",
        ),
        SpeedPillar(
            PlaygroundIconKind.Target, "Perfect-hash dispatch", "Perfect hash",
            "At compile time Ghost's PerfectHashFinder searches multiplier/shift/table-size combinations until it finds one where every one of your field names lands in its own table slot with zero collisions — the same algorithm this Playground's dispatch-table preview runs live, just against ghost-compiler's real search space instead of a browser-side clone.",
            "En compile time, el PerfectHashFinder de Ghost busca combinaciones de multiplier/shift/tamaño de tabla hasta encontrar una donde cada uno de tus nombres de campo cae en su propio slot sin colisiones — el mismo algoritmo que corre en vivo la vista previa de dispatch table de este Playground, solo que contra el espacio de búsqueda real de ghost-compiler en vez de un clon del lado del navegador.",
            "selectName() becomes: hash the incoming key's bytes, multiply, shift, mask — one integer computation that lands straight on the matching field index. No probing, no bucket chains, no equals() calls, because the hash function was chosen specifically so collisions can't happen for this DTO's field set.",
            "selectName() se reduce a: hashear los bytes de la key entrante, multiplicar, shiftear, enmascarar — una sola cuenta entera que cae directo en el índice del campo correspondiente. Sin probing, sin cadenas de buckets, sin llamadas a equals(), porque la función hash se eligió específicamente para que no puedan darse colisiones en el set de campos de este DTO.",
            "Jackson's BeanPropertyMap and Gson's reflective field lookup both hash the key string and then probe an open-addressing map, falling back to equals() on collision. Moshi binary-searches a sorted names array (O(log n) comparisons). Both are still doing real work per key; Ghost's table lookup is O(1) with the collision case designed out ahead of time.",
            "El BeanPropertyMap de Jackson y el lookup reflexivo de Gson hashean la key y después hacen probing en un mapa open-addressing, cayendo a equals() si hay colisión. Moshi hace búsqueda binaria sobre un array de nombres ordenado (O(log n) comparaciones). Ambos siguen haciendo trabajo real por key; el lookup de tabla de Ghost es O(1) con el caso de colisión eliminado de antemano.",
        ),
        SpeedPillar(
            PlaygroundIconKind.Bytes, "Byte-first UTF-8", "Byte-first UTF-8",
            "GhostJsonFlatReader and the Okio-streaming GhostJsonReader both walk the raw ByteArray/BufferedSource directly — whitespace skipping, quote scanning, and number parsing all operate on bytes, with SWAR (SIMD-within-a-register) tricks scanning several bytes per comparison on the hot loops instead of one char at a time.",
            "GhostJsonFlatReader y el GhostJsonReader que streamea sobre Okio recorren el ByteArray/BufferedSource crudo directamente — el salteo de whitespace, el escaneo de comillas y el parseo de números operan todos sobre bytes, con trucos SWAR (SIMD-within-a-register) que comparan varios bytes a la vez en los loops calientes en vez de un char por vez.",
            "Network stacks (OkHttp, Ktor, NSURLSession) already hand you bytes off the wire. Staying on bytes end-to-end means the payload is scanned exactly once — no separate pass to build a String first, no second scan to tokenize it.",
            "Los stacks de red (OkHttp, Ktor, NSURLSession) ya te entregan bytes de la conexión. Quedarse en bytes de punta a punta significa que el payload se escanea una sola vez — sin un pase separado para armar un String primero, sin un segundo escaneo para tokenizarlo.",
            "String-first APIs (classic Gson/Jackson entry points, org.json) decode the entire byte payload to a UTF-16 String before parsing even starts — that's a full copy plus a transcode of every byte, doubling memory traffic before the real work begins on large JSON.",
            "Las APIs String-first (los puntos de entrada clásicos de Gson/Jackson, org.json) decodean todo el payload de bytes a un String UTF-16 antes de que el parseo siquiera arranque — eso es una copia completa más una transcodificación de cada byte, duplicando el tráfico de memoria antes de que empiece el trabajo real en JSON grande.",
        ),
        SpeedPillar(
            PlaygroundIconKind.TextChannel, "Native textChannel", "textChannel nativo",
            "When @GhostSerialization(textChannel = true) is set (the default), KSP also emits a GhostJsonStringReader/Writer overload that reads UTF-16 chars straight out of the Kotlin String's own backing storage — the exact same field-dispatch and hash logic as the byte path, just walking chars instead of bytes.",
            "Cuando @GhostSerialization(textChannel = true) está activo (el default), KSP también emite un overload GhostJsonStringReader/Writer que lee chars UTF-16 directo del backing storage del propio String de Kotlin — la misma lógica de dispatch y hash que el path de bytes, solo que recorriendo chars en vez de bytes.",
            "Android/KMP UI state, in-memory caches, and anything coming out of a database TEXT column already hold JSON as a String. Reading that String directly skips a UTF-8 encode you'd otherwise pay for just to hand Ghost bytes it would immediately have to decode back to chars.",
            "El estado de UI en Android/KMP, los caches en memoria, y cualquier cosa que salga de una columna TEXT de base de datos ya tienen el JSON como String. Leer ese String directamente evita un encode a UTF-8 que de otra forma pagarías solo para darle a Ghost bytes que igual tendría que decodificar de vuelta a chars.",
            "Byte-only parsers UTF-8-encode the whole String just to parse it, then usually decode substrings back to String again for every field value — Ghost's text channel removes both round-trips for producers/consumers that were already String-based to begin with.",
            "Los parsers solo-bytes le hacen encode a UTF-8 a todo el String solo para parsearlo, y después normalmente decodean substrings de vuelta a String otra vez por cada valor de campo — el canal de texto de Ghost elimina ambos round-trips para productores/consumidores que ya partían de un String.",
        ),
        SpeedPillar(
            PlaygroundIconKind.Order, "In-order prediction", "Predicción in-order",
            "Every reader tracks an expectedFieldIndex counter. Before hashing a key at all, Ghost cheaply compares the incoming bytes against the field it expects next (based on your data class's declared property order) — a match skips hashing entirely and jumps straight to that field's decode call.",
            "Cada reader lleva un contador expectedFieldIndex. Antes de siquiera hashear una key, Ghost compara barato los bytes entrantes contra el campo que espera a continuación (según el orden de propiedades declarado en tu data class) — si coincide, se salta el hash por completo y salta directo al decode de ese campo.",
            "Real producers are rarely adversarial: a server serializing the same DTO type request after request emits keys in the same stable order every time. Prediction turns that common case into a handful of byte comparisons instead of a hash computation on every single key.",
            "Los productores reales rara vez son adversariales: un servidor que serializa el mismo tipo de DTO una y otra vez emite las keys en el mismo orden estable siempre. La predicción convierte ese caso común en un puñado de comparaciones de bytes en vez de una cuenta de hash en cada key.",
            "Every other parser in this comparison hashes (or otherwise looks up) every key on every decode, with no memory of what \"usually\" comes next. Ghost falls back to the exact same perfect-hash table those parsers always use the moment a key doesn't match the prediction — shuffled input never gets slower than the hash-only baseline, in-order input gets faster.",
            "El resto de los parsers de esta comparación hashean (o buscan de otra forma) cada key en cada decode, sin memoria de qué \"suele\" venir después. Ghost cae a la misma tabla perfect-hash que esos parsers usan siempre en el momento en que una key no coincide con la predicción — el input desordenado nunca es más lento que la base solo-hash, y el input en orden se vuelve más rápido.",
        ),
        SpeedPillar(
            PlaygroundIconKind.Pool, "Pooled readers & writers", "Pools",
            "GhostPools hands out reader/writer instances backed by reusable scratch buffers instead of allocating fresh ones per call — a thread-local pool on JVM/Android/Native (via expect/actual), and a single reusable instance on Wasm/JS, which are single-threaded and have no concept of thread-local storage.",
            "GhostPools entrega instancias de reader/writer respaldadas por buffers scratch reutilizables en vez de allocar unas nuevas por llamada — un pool thread-local en JVM/Android/Native (vía expect/actual), y una única instancia reutilizable en Wasm/JS, que son single-threaded y no tienen noción de almacenamiento thread-local.",
            "A hot endpoint doing thousands of encode/decode calls per second amortizes its buffer allocation to effectively zero after warmup — the scratch array just gets reused and, when a payload is bigger than usual, grows once and stays grown rather than reallocating on the next call.",
            "Un endpoint caliente haciendo miles de llamadas encode/decode por segundo amortiza su allocación de buffers a prácticamente cero después del warmup — el array scratch simplemente se reutiliza y, cuando un payload es más grande de lo usual, crece una vez y se queda así en vez de reallocar en la próxima llamada.",
            "Allocating a fresh parser/writer (and its internal buffers) on every request is the default in most reflection-based libraries. Under load that's continuous garbage generation — pooling is what keeps Ghost's tail latency flat instead of spiking with GC pauses as QPS climbs.",
            "Allocar un parser/writer nuevo (y sus buffers internos) en cada request es el default en la mayoría de las librerías basadas en reflexión. Bajo carga eso es generación continua de basura — el pooling es lo que mantiene la latencia de cola de Ghost plana en vez de picar con pausas de GC a medida que sube el QPS.",
        ),
        SpeedPillar(
            PlaygroundIconKind.Nullable, "Fused nullables", "Nullables fused",
            "A nullable Int property compiles to a call like nextIntOrNull() — one generated function that peeks the next token, and either returns a boxed null in a single branch or reads the primitive directly, instead of a separate isNull() check followed by a conditional read-and-box.",
            "Una propiedad Int nullable compila a una llamada como nextIntOrNull() — una única función generada que espía el próximo token y, con un solo branch, o devuelve null o lee el primitivo directamente, en vez de un isNull() separado seguido de un read-and-box condicional.",
            "DTOs with many optional fields (partial updates, PATCH bodies, sparse API responses) hit this path constantly. Fusing the null-check into the read removes a branch and, on the common non-null path, a redundant re-check of state the reader already inspected once.",
            "Los DTOs con muchos campos opcionales (updates parciales, bodies de PATCH, respuestas de API dispersas) pasan por este camino todo el tiempo. Fusionar el null-check con el read elimina un branch y, en el camino común no-null, una re-verificación redundante de un estado que el reader ya inspeccionó una vez.",
            "Hand-rolled or reflective decoders typically do isNull ? null : box(readInt()) as two separate operations — an extra branch and, in JVM-flavored code, an extra virtual call into the boxing machinery that Ghost's single fused instruction avoids.",
            "Los decoders escritos a mano o reflexivos suelen hacer isNull ? null : box(readInt()) como dos operaciones separadas — un branch extra y, en código con sabor JVM, una llamada virtual extra a la maquinaria de boxing que la instrucción única y fusionada de Ghost evita.",
        ),
        SpeedPillar(
            PlaygroundIconKind.Write, "Precomputed write headers", "Headers precomputados",
            "KSP bakes each field's JSON header — the opening quote, the field name, the closing quote, and the colon — into a byte/char literal embedded in the generated writer as a single writeNameRaw() call, instead of concatenating those pieces from a String field name at runtime on every encode.",
            "KSP hornea el header JSON de cada campo — la comilla de apertura, el nombre del campo, la comilla de cierre y los dos puntos — como un literal de bytes/chars embebido en el writer generado, en una sola llamada a writeNameRaw(), en vez de concatenar esas piezas a partir del nombre del campo en runtime en cada encode.",
            "The encode path becomes a flat, predictable sequence of raw-byte copies with no string-building in between — exactly the kind of code the JIT/ART (or Wasm's own optimizing tier) likes to keep hot and inlined, with no allocation between one field's header and the next.",
            "El camino de encode se vuelve una secuencia plana y predecible de copias de bytes crudos sin armado de strings en el medio — justo el tipo de código que al JIT/ART (o al tier optimizador de Wasm) le gusta mantener caliente e inlineado, sin allocaciones entre el header de un campo y el siguiente.",
            "Building \"key\": from scratch on every write — as most reflective or string-template-based serializers do — allocates and copies char/byte data repeatedly for the exact same bytes every single call, since the field name never actually changes between calls.",
            "Armar \"key\": desde cero en cada write — como hacen la mayoría de los serializers reflexivos o basados en templates de strings — alloca y copia datos char/byte repetidamente para exactamente los mismos bytes en cada llamada, ya que el nombre del campo nunca cambia entre llamadas.",
        ),
    )
}
